# -*- coding: utf-8 -*-
"""text_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PKtjQecoKhMhxrk1ZQ8Aluk_olqUr40_
"""

!pip install gTTS

from gtts import gTTS
import librosa

text_to_speech="Hello Everyone This is Jeffrina Here "
language="en"

gtts_object=gTTS(text=text_to_speech,
                 lang=language,
                 slow= False)

gtts_object.save("my_voc.wav")

from IPython.display import Audio

data1,Fs1=librosa.load('/content/my_voc.wav')

Audio("/content/my_voc.wav")

import numpy as np
from scipy.io import wavfile
import matplotlib.pyplot as plt

plt.figure()
plt.plot(data1)
plt.xlabel('sample Index')
plt.ylabel('Amplitude')
plt.title('waveform of text_to_speech')
plt.show

text_to_speech_tam=" bist du gut  "
language_tam="de"

gtts_object=gTTS(text=text_to_speech_tam,
                 lang=language_tam,
                 slow= False)

gtts_object.save("my_tam.wav")

from IPython.display import Audio

data2,Fs2=librosa.load('/content/my_tam.wav')

plt.figure()
plt.plot(data2)
plt.xlabel('sample Index')
plt.ylabel('Amplitude')
plt.title('waveform of text_to_speech_tam')
plt.show

Audio("/content/my_tam.wav")



text_to_speech_italy=" Voglio bene alla tua mamma "
language_italy="it"

gtts_object=gTTS(text=text_to_speech_italy,
                 lang=language_italy,
                 slow= False)

gtts_object.save("my_italy.wav")

from IPython.display import Audio

Audio("/content/my_italy.wav")



!pip install SpeechRecognition

import speech_recognition as sr

r=sr.Recognizer()

with sr.WavFile("/content/audio1.wav") as source:
  audio_to_text=r.listen(source)

  try:
      text=r.recognize_google(audio_to_text)
      print("Convertion is started")
      print (text)

  except:
       print("Oops try again")

with sr.WavFile("/content/audio2.wav") as source:
  audio_to_text=r.listen(source)

  try:
      text=r.recognize_google(audio_to_text)
      print("Started the text")
      print (text)

  except:
       print("Oops try again")

with sr.WavFile("/content/song.wav") as source:
  audio_to_text=r.listen(source)

  try:
      text=r.recognize_google(audio_to_text)
      print("Started the text")
      print (text)

  except:
       print("Oops try again")